name: 'Download dist'
# Downloads a 'dist' directory artifact that was uploaded in an earlier step
# We control this with an environment variable to allow for easier global configuration.
runs:
  using: "composite"
  steps: 
    - name: Download dist
      if: ${{ env.DOWNLOAD_DIST == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
