name: Test caching with Kotlin DSL

on:
  pull_request:
    types: [assigned, review_requested]
  push:
    paths:
      - '.github/**'
      - 'dist/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

env:
  GRADLE_BUILD_ACTION_CACHE_KEY_PREFIX: ${{ github.workflow }}#${{ github.run_number }}:${{ github.run_attempt }}-
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  seed-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: ./
      - name: Build kotlin-dsl project
        working-directory: .github/workflow-samples/kotlin-dsl
        run: ./gradlew build

  verify-build:
    needs: seed-build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: ./
      - name: Build kotlin-dsl project
        working-directory: .github/workflow-samples/kotlin-dsl
        run: ./gradlew build --offline
